export const gameConfig = {
  normalSwipeSensitivity: 1.15,
  telescopeSwipeSensitivity: 0.22,
  densityThresholds: {
    few: 1,
    medium: 2,
    many: 4,
  },
  densityEffect: {
    colors: {
      none: '#7f8790',
      few: '#8bd7ff',
      medium: '#ffe66d',
      many: '#ff9f43',
    },
    glowOpacity: { none: 0, few: 0.1, medium: 0.15, many: 0.22 },
    edgeSpanFraction: 0.22,
    clearPadding: 10,
    featherWidth: 32,
    transitionMs: 140,
  },
  constellationButton: {
    minimumStars: 2,
    diameter: 176,
    centerRightInset: 24,
    centerBottomInset: 16,
    hiddenOffset: 110,
    springTension: 100,
    springFriction: 11,
    showDelayMs: 250,
    hideDelayMs: 400,
  },
  compass: {
    // Alpha-boundary samples of mountain_new.png after its configured rotation, N through NW.
    ridgeElevationDegrees: [-12.75, -13.25, -12.75, -13, -12.5, -12.25, -13, -12.5],
    elevationOffsetDegrees: 1.5,
    color: '#d9e2e5',
    opacity: 0.68,
    fontSize: 13,
    edgeFade: 32,
  },
  constellationEditor: {
    bandRadius: 0.09,
    brushSmoothing: { enabled: true, slowTimeMs: 40, fastTimeMs: 6, fastDistancePx: 12 },
    brushTexture: { spacing: 0.002, width: 0.0038, edgeRoughness: 0.22, minimumOpacity: 0.58 },
    strokeColor: '#ffffff',
    guideColor: '#a8c8ff',
    guideOpacity: 0.1,
    stampSize: 0.14,
    minStampSize: 0.09,
    maxStampSize: 0.25,
    pointSpacing: 0.0015,
    maxNameLength: 40,
    starHitRadius: 26,
    snapRadius: 34,
    lineHitRadius: 14,
    lineWidth: 1.5,
    lineOpacity: 0.4,
    tapSlop: 8,
    minZoom: 0.7,
    maxZoom: 4,
    lineColor: '#c4e7eb',
    previewColor: '#ffdc8c',
  },
  prototypeStarSpacingScale: 1.2,
  starTapRadius: 24,
  telescopeStarScale: 2,
  telescopeStarTapRadius: 32,
  starFocusDurationMs: 420,
  pinchSwitchRatio: 1.25,
  pinchMinTravel: 28,
  panorama: {
    verticalFovDegrees: 74,
    telescopeZoom: 4.6,
    worldUnitsPerRadian: 520,
    mountainLongitudeOffsetTurns: 0,
    // Asset-to-world rotation: the mountain image's +Z ground points toward world -Y.
    mountainRotationDegrees: { x: 90, y: 0, z: 0 },
  },
  deviceMotion: {
    updateIntervalMs: 50,
    smoothingFactor: 0.35,
    maxStepRadians: 0.12,
    recenterDurationMs: 280,
  },
  dowsingMaxDistance: 780,
} as const;
